include: "rules/common.smk"
include: "rules/raw_data/genome_sequence.smk"
include: "rules/raw_data/genome_annotation.smk"
include: "rules/agat/gff2gtf.smk"
include: "rules/raw_data/genome_variation.smk"
include: "rules/gatk/picard_dict.smk"
include: "rules/samtools/faidx.smk"
include: "rules/raw_data/blacklist.smk"
include: "rules/bedtools/merge_blacklist.smk"
include: "rules/pyroe/id_to_name.smk"


rule target:
    input:
        unpack(get_targets),
    log:
        "logs/targets.log",
    benchmark:
        "benchmark/targets.tsv"
