# configuration of display in snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog

usage:
  mandatory-flags:
    desc: Download and index Ensembl genome files
    flags:
  software-stack-deployment:
    conda: true
    singularity: false
    singularity+conda: false
  report: false
