# General options
cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 5
jobs: 60
use-conda: true
use-singularity: true
use-env-modules: true
printshellcmds: true

# Absolute paths to shared BiGR@Flamingo cluster
conda-prefix: /mnt/beegfs/pipelines/unofficial-snakemake-wrappers/shared_install/
singularity-prefix: /mnt/beegfs/pipelines/unofficial-snakemake-wrappers/singularity/

# Default job resources
default-resources:
  - runtime=90
  - mem_mb=512
  - partition=shortq
  - tmpdir=tmp

# Special job resources
set-resources:
  - bedtools_merge_blacklist:
    - runtime=10
    - mem_mn=3072
  - samtools_index:
    - runtime=10
    - mem_mb=1024
