default-resources:
  runtime: 90
  mem_mb: 512

set-resources:
  bedtools_merge_blacklist:
    mem_mb: 3072
    runtime: 10
  samtools_index:
    mem_mb: 1024
    runtime: 10
  picard_create_dict:
    mem_mb: 4096
    runtime: 10
  agat_gff2gtf:
    mem_mb: 2048
    runtime: 15