$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

genomes:
  type: string
  description: Path to the CSV file defining genome properties


params:
  type: object
  description: Optional parameters

  fair_genome_indexer_ucsc_gtf_to_genepred:
    type: str
    description: Optional parameters for ucsc gtfToGenePred

  fair_genome_indexer_agat_convert_sp_gff2tsv:
    type: str
    description: Optional parameters for agat_convert_sp_gff2tsv.pl

  fair_genome_indexer_xsv_select_t2g_columns:
    type: str
    description: Optional parameters for xsv select

  fair_genome_indexer_xsv_fmt_t2g:
    type: str
    description: Optional parameters for xsv fmt

  fair_genome_indexer_tabix_index_dbsnp:
    type: str
    description: Optional parameters for tabix index

  fair_genome_indexer_tabix_index_dbsnp_index_raw_dbsnp:
    type: str
    description: Optional parameters for tabix index

  fair_genome_indexer_samtools_index:
    type: str
    description: Optional parameters for samtools faidx

  fair_genome_indexer_pyroe_id_to_name:
    type: str
    description: Optional parameters for pyroe idtoname

  fair_genome_indexer_rsync_make_fasta_available:
    type: str
    description: Optional parameters for rsync

  fair_genome_indexer_pyfaidx_filter_out_noncanonical_chromosomes:
    type: object
    description: pyfaidx optional parameters for each subtype of sequences
    
    dna:
      type: str
      description: pyfaidx optional parameters for DNA sequences

    cdna:
      type: str
      description: pyfaidx optional parameters for cDNA sequences

    transcripts:
      type: str
      description: pyfaidx optional parameters for transcripts DNA sequences

  fair_genome_indexer_picard_create_dict:
    type: str
    description: Picard CreateSequenceDictionary optional parameters

  fair_genome_indexer_gffread_transcripts:
    type: str
    description: GffRead optional parameters for transcripts extraction

  fair_genome_indexer_gffread_cdna:
    type: str
    description: GffRead optional parameters for cDNA extraction

  fair_genome_indexer_wget:
    type: str
    description: Optional parameters for wget

  fair_genome_indexer_bedtools_merge_blacklist:
    type: str
    description: Optional parameters for bedtools merge

  fair_genome_indexer_bcftools_filter_non_canonical_chrom:
    type: str
    description: Optional parameters for bcftools filter

  fair_genome_indexer_pyfaidx_fasta_dict_to_bed:
    type: str
    description: Optional parameters for pyfaidx 

  fair_genome_indexer_agat_sq_filter_feature_from_fasta:
    type: str
    description: Optional parameters for agat_sq_filter_feature_from_fasta.pl

  fair_genome_indexer_agat_sp_filter_feature_by_attribute_value:
    type: str
    description: Optional parameters for agat_sp_filter_feature_by_attribute_value.pl

  fair_genome_indexer_agat_convert_sp_gff2gtf:
    type: str
    escription: Optional parameters for agat_convert_sp_gff2gtf.pl

  fair_genome_indexer_agat_config:
    type: object
    description: Mapping of all agat parameters